version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: "devcontainers"
    directory: src/r-ver
    schedule:
      interval: daily

  - package-ecosystem: "devcontainers"
    directory: src/rstudio
    schedule:
      interval: daily
