name: Build and push images

on:
  workflow_dispatch:
    inputs:
      push:
        type: boolean
        description: push the devcontainer images?
        required: true
        default: false
  pull_request:
    branches:
      - main
    paths:
      - src/**.devcontainer.json
      - src/**Dockerfile
      - src/**/assets/**
      - "!**.md"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            r-ver: ./**/r-ver/**
            rstudio: ./**/rstudio/**

  generate-matrix:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-json
        run: |
          jsonfile="build/matrix.json"
          echo ::set-output name=json::${jsonfile}
          echo ${jsonfile}
      - id: set-matrix
        run: |
          jsoncontent=$(jq -r 'tostring' ${{ steps.set-json.outputs.json }})
          echo ::set-output name=matrix::"${jsoncontent}"
          echo "${jsoncontent}"

  generate-matrix-pr:
    if: ${{ github.event_name == 'pull_request' }}
    needs:
      - detect-changes
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-json
        run: |
          jsonfile="build/matrix.json"
          echo ::set-output name=json::${jsonfile}
          echo ${jsonfile}
      - id: set-matrix
        run: |
          regex=$(echo '${{ needs.detect-changes.outputs.src }}' | jq '.|join("|")' -r)
          jsoncontent=$(jq -r '{ include: [ .include[] | select(.src_name | test("'${regex}'")) ] } | tostring' ${{ steps.set-json.outputs.json }})
          echo ::set-output name=matrix::"${jsoncontent}"
          echo "${jsoncontent}"

  build-pr:
    needs:
      - generate-matrix-pr
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix-pr.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up devcontainer cli
        run: npm install -g @devcontainers/cli
      - name: Test build
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          PLATFORM=linux/amd64 \
          SRC_NAME=${{ matrix.src_name }} \
          IMAGE_NAME=${{ matrix.image_name }} \
          VARIANT=${{ matrix.variant }} \
          make devcontainer

  build-push:
    needs:
      - generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix-pr.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up devcontainer cli
        run: npm install -g @devcontainers/cli
      - name: Build and push Docker images
        run: |
          SRC_NAME=${{ matrix.src_name }} \
          IMAGE_NAME=${{ matrix.image_name }} \
          VARIANT=${{ matrix.variant }} \
          DEVCON_BUILD_OPTION=--push\ ${{ inputs.push }} \
          make devcontainer
